// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HeroiconsOutlineDownload: typeof import('~icons/heroicons-outline/download')['default']
    HeroiconsOutlineX: typeof import('~icons/heroicons-outline/x')['default']
    InstallButton: typeof import('./src/components/InstallButton.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    Stats: typeof import('./src/components/Stats.vue')['default']
    SWBanner: typeof import('./src/components/SWBanner.vue')['default']
  }
}

export {}
